# Generated by Django 5.2.6 on 2025-09-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
                ('created_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
            ],
        ),
    ]
