# Generated by Django 5.2.6 on 2025-09-26 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
