# Generated by Django 5.2.6 on 2025-09-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tables_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
