# Generated by Django 5.2.6 on 2025-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_tables_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tables',
            name='duration',
        ),
        migrations.AddField(
            model_name='tables',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
